# Book My Show Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
  labels:
    app: bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: bms-container
        image: ${DOCKER_IMAGE}  # Placeholder for dynamic replacement
        ports:
        - containerPort: 3000  # Replace with the port your app runs on

---
# Book My Show Application Service
apiVersion: v1
kind: Service
metadata:
  name: bms-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: bms