name: End to End CI/CD for Book My Show Application

on:
  push:
    branches:
      - "master"
      - "main"
      - "task/**"
  pull_request:
    branches:
      - "master"
      - "main"
      - "task/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # inputs:
    #   is_push_image:
    #     description: "Do you want to push Docker image to Docker Hub ?"
    #     required: true
    #     default: true
    #     type: boolean
    #   is_deploy_image:
    #     description: "Do you want to deploy Docker image to AKS ?"
    #     required: true
    #     default: false
    #     type: boolean

# permissions:
#   id-token: write
#   contents: read

jobs:
# # Build & Push docker image to Docker Hub
#   docker_build-push:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
      
#       - name: Docker Build
#         run: |
#           docker build -t kcmchandramoulli/bookmyshow:test3 bookmyshow-app

#       - name: Docker Push
#         run: |
#           docker push kcmchandramoulli/bookmyshow:test3

# Create AKS with terraform
  iac-aks-creation:
    runs-on: ubuntu-latest
    env:
      TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialization
        run: |
          cd aks_tf_scripts
          terraform init

      - name: Terraform Plan
        run: |
          cd aks_tf_scripts
          terraform plan

      - name: Terraform Apply
        run: |
          cd aks_tf_scripts
          terraform apply -auto-approve