name: End to End CI/CD for Book My Show Application

on:
  push:
    branches:
      - "master"
      - "main"
      - "task/**"
  pull_request:
    branches:
      - "master"
      - "main"
      - "task/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # inputs:
    #   is_push_image:
    #     description: "Do you want to push Docker image to Docker Hub ?"
    #     required: true
    #     default: true
    #     type: boolean
    #   is_deploy_image:
    #     description: "Do you want to deploy Docker image to AKS ?"
    #     required: true
    #     default: false
    #     type: boolean

# permissions:
#   id-token: write
#   contents: read

jobs:
  # maven-compile:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: setup JDK 17
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: '17'
  #         distribution: 'temurin'
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '23'
  #     - name: Verify tools Installation
  #       run: |
  #         java -version
  #         node -v
  #         npm -v

  #     - name: Install dependencys
  #       run: |
  #         cd bookmyshow-app
  #         ls -la
  #         if [ -f "package.json" ]; then
  #           npm install
  #         else
  #           echo "No package.json file found."
  #           exit 1
  #         fi

# Build & Push docker image to Docker Hub
  docker_build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker Build
        run: |
          docker build -t kcmchandramoulli/bookmyshow:test1 bookmyshow-app

      - name: Docker Push
        run: |
          docker push kcmchandramoulli/bookmyshow:test1